import "./globals.css";

import { Footer } from "./components/Shared/Footer";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { Navbar } from "./components/Shared/Navbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased flex flex-col text-white`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
